/**
 * Phase 1: Unit Tests for Scoring Engine
 *
 * Tests calcCourseHandicap, calcStrokesOnHole, calcNetScore, calcPlayingHandicap
 * against verified values from TESTING-PLAN.md (generated by Opus 4.6, 2026-02-21).
 *
 * These tests import scoring functions directly — no browser, no network.
 * Run with: npx playwright test tests/scoring/20-unit-scoring.spec.ts
 */

import { test, expect } from '@playwright/test'
import {
  calcCourseHandicap,
  calcStrokesOnHole,
  calcNetScore,
  calcPlayingHandicap,
} from '../../src/lib/scoring/handicap'

// ---------------------------------------------------------------------------
// Section 1: Course Handicap Verification (33 values, all 3 days)
// Formula: ROUND(HI × (Slope / 113) + (Rating - Par))
// All values verified against Supabase player_tee_assignments.course_handicap
// ---------------------------------------------------------------------------

test.describe('Course Handicap — Day 1: Terra Lago North (Par 72)', () => {
  const cases: [string, number, number, number, number, number][] = [
    // [player, HI, slope, rating, par, expectedCH]
    ['Ryan',    8.9,  139, 74.7, 72, 14],
    ['Kiki',    9.3,  132, 71.9, 72, 11],
    ['Mack',   10.0,  132, 71.9, 72, 12],
    ['Bruce',  10.6,  139, 74.7, 72, 16],
    ['Matthew',11.0,  139, 74.7, 72, 16],
    ['C-Pat',  11.5,  139, 74.7, 72, 17],
    ['Eric',   13.5,  132, 71.9, 72, 16],
    ['Ben',    19.0,  132, 71.9, 72, 22],
    ['Gary',   22.1,  132, 71.9, 72, 26],
    ['Chris',  30.0,  132, 71.9, 72, 35],
    ['Jauch',  36.0,  132, 71.9, 72, 42],
  ]

  for (const [name, hi, slope, rating, par, expected] of cases) {
    test(`${name}: HI=${hi} → CH=${expected}`, () => {
      expect(calcCourseHandicap(hi, slope, rating, par)).toBe(expected)
    })
  }
})

test.describe('Course Handicap — Day 2: PGA West Mountain (Par 72)', () => {
  const cases: [string, number, number, number, number, number][] = [
    ['Ryan',    8.9,  135, 72.8, 72, 11],
    ['Kiki',    9.3,  122, 68.3, 72, 6],
    ['Mack',   10.0,  132, 71.8, 72, 11],
    ['Bruce',  10.6,  132, 71.8, 72, 12],
    ['Matthew',11.0,  135, 72.8, 72, 14],
    ['C-Pat',  11.5,  122, 68.3, 72, 9],
    ['Eric',   13.5,  129, 70.8, 72, 14],
    ['Ben',    19.0,  129, 70.8, 72, 20],
    ['Gary',   22.1,  122, 68.3, 72, 20],
    ['Chris',  30.0,  129, 70.8, 72, 33],
    ['Jauch',  36.0,  122, 68.3, 72, 35],
  ]

  for (const [name, hi, slope, rating, par, expected] of cases) {
    test(`${name}: HI=${hi} → CH=${expected}`, () => {
      expect(calcCourseHandicap(hi, slope, rating, par)).toBe(expected)
    })
  }
})

test.describe('Course Handicap — Day 3: Eagle Falls (Par 72)', () => {
  const cases: [string, number, number, number, number, number][] = [
    // All on Hawk tees: rating=70.0, slope=127, par=72
    ['Ryan',    8.9,  127, 70.0, 72, 8],
    ['Kiki',    9.3,  127, 70.0, 72, 8],
    ['Mack',   10.0,  127, 70.0, 72, 9],
    ['Bruce',  10.6,  127, 70.0, 72, 10],
    ['Matthew',11.0,  127, 70.0, 72, 10],
    ['C-Pat',  11.5,  127, 70.0, 72, 11],
    ['Eric',   13.5,  127, 70.0, 72, 13],
    ['Ben',    19.0,  127, 70.0, 72, 19],
    ['Gary',   22.1,  127, 70.0, 72, 23],
    ['Chris',  30.0,  127, 70.0, 72, 32],
    ['Jauch',  36.0,  127, 70.0, 72, 38],
  ]

  for (const [name, hi, slope, rating, par, expected] of cases) {
    test(`${name}: HI=${hi} → CH=${expected}`, () => {
      expect(calcCourseHandicap(hi, slope, rating, par)).toBe(expected)
    })
  }
})

// ---------------------------------------------------------------------------
// Section 2: Stroke Allocation — Boundary Conditions
// Tests the key breakpoints in calcStrokesOnHole
// ---------------------------------------------------------------------------

test.describe('Stroke Allocation — calcStrokesOnHole', () => {
  // CH=0: gets 0 strokes on ALL holes
  test.describe('CH=0 (scratch)', () => {
    test('rank 1: 0 strokes', () => expect(calcStrokesOnHole(0, 1)).toBe(0))
    test('rank 18: 0 strokes', () => expect(calcStrokesOnHole(0, 18)).toBe(0))
  })

  // CH=1: gets 1 stroke on rank-1 hole only
  test.describe('CH=1', () => {
    test('rank 1: 1 stroke', () => expect(calcStrokesOnHole(1, 1)).toBe(1))
    test('rank 2: 0 strokes', () => expect(calcStrokesOnHole(1, 2)).toBe(0))
    test('rank 18: 0 strokes', () => expect(calcStrokesOnHole(1, 18)).toBe(0))
  })

  // CH=18: gets 1 stroke on every hole
  test.describe('CH=18', () => {
    test('rank 1: 1 stroke', () => expect(calcStrokesOnHole(18, 1)).toBe(1))
    test('rank 18: 1 stroke', () => expect(calcStrokesOnHole(18, 18)).toBe(1))
  })

  // CH=19: gets 2 strokes on rank-1, 1 stroke on ranks 2-18
  test.describe('CH=19', () => {
    test('rank 1: 2 strokes', () => expect(calcStrokesOnHole(19, 1)).toBe(2))
    test('rank 2: 1 stroke', () => expect(calcStrokesOnHole(19, 2)).toBe(1))
    test('rank 18: 1 stroke', () => expect(calcStrokesOnHole(19, 18)).toBe(1))
  })

  // CH=36: gets 2 strokes on ALL holes
  test.describe('CH=36', () => {
    test('rank 1: 2 strokes', () => expect(calcStrokesOnHole(36, 1)).toBe(2))
    test('rank 18: 2 strokes', () => expect(calcStrokesOnHole(36, 18)).toBe(2))
  })

  // CH=37: gets 3 strokes on rank-1, 2 on ranks 2-18
  test.describe('CH=37', () => {
    test('rank 1: 3 strokes', () => expect(calcStrokesOnHole(37, 1)).toBe(3))
    test('rank 2: 2 strokes', () => expect(calcStrokesOnHole(37, 2)).toBe(2))
    test('rank 18: 2 strokes', () => expect(calcStrokesOnHole(37, 18)).toBe(2))
  })

  // CH=42 (Jauch Day 1 — highest CH in the group)
  // Gets 2 strokes everywhere + 3 strokes on holes ranked ≤ (42-36)=6
  test.describe('CH=42 (Jauch Day 1)', () => {
    test('rank 1: 3 strokes', () => expect(calcStrokesOnHole(42, 1)).toBe(3))
    test('rank 6: 3 strokes', () => expect(calcStrokesOnHole(42, 6)).toBe(3))
    test('rank 7: 2 strokes', () => expect(calcStrokesOnHole(42, 7)).toBe(2))
    test('rank 18: 2 strokes', () => expect(calcStrokesOnHole(42, 18)).toBe(2))
  })

  // Verify Day 1 Terra Lago spot-checks from Section 2 of TESTING-PLAN
  // Hole handicap ranks for Terra Lago North (from table header):
  // H1=R9, H2=R15, H3=R17, H4=R7, H5=R1, H6=R11, H7=R13, H8=R5, H9=R3
  // H10=R10, H11=R16, H12=R18, H13=R8, H14=R2, H15=R12, H16=R14, H17=R6, H18=R4

  test.describe('Day 1 spot-checks (Terra Lago North ranks)', () => {
    // Jauch CH=42: H5 rank=1 → 3 strokes; H8 rank=5 → 3 strokes; H9 rank=3 → 3 strokes
    test('Jauch CH=42 on rank-1 hole (H5): 3 strokes', () => expect(calcStrokesOnHole(42, 1)).toBe(3))
    test('Jauch CH=42 on rank-5 hole (H8): 3 strokes', () => expect(calcStrokesOnHole(42, 5)).toBe(3))
    test('Jauch CH=42 on rank-7 hole (H4): 2 strokes', () => expect(calcStrokesOnHole(42, 7)).toBe(2))
    test('Jauch CH=42 on rank-18 hole (H12): 2 strokes', () => expect(calcStrokesOnHole(42, 18)).toBe(2))

    // Ben CH=22: gets 2 strokes on holes ranked ≤ (22-18)=4
    // rank-1 (H5)=2, rank-5 (H8)=1, rank-4 (H18)=2, rank-15 (H2)=1
    test('Ben CH=22 on rank-1 hole (H5): 2 strokes', () => expect(calcStrokesOnHole(22, 1)).toBe(2))
    test('Ben CH=22 on rank-5 hole (H8): 1 stroke', () => expect(calcStrokesOnHole(22, 5)).toBe(1))
    test('Ben CH=22 on rank-4 hole (H18): 2 strokes', () => expect(calcStrokesOnHole(22, 4)).toBe(2))

    // Ryan CH=14: gets 1 stroke on holes ranked ≤ 14
    test('Ryan CH=14 on rank-14 hole (H16): 1 stroke', () => expect(calcStrokesOnHole(14, 14)).toBe(1))
    test('Ryan CH=14 on rank-15 hole (H2): 0 strokes', () => expect(calcStrokesOnHole(14, 15)).toBe(0))
    test('Ryan CH=14 on rank-17 hole (H3): 0 strokes', () => expect(calcStrokesOnHole(14, 17)).toBe(0))
  })
})

// ---------------------------------------------------------------------------
// Section 3: Net Score Calculation — calcNetScore
// Formula: min(gross - strokes, par + strokes + netMaxOverPar)
// ---------------------------------------------------------------------------

test.describe('Net Score — calcNetScore', () => {
  // Basic: no strokes, no cap triggered
  test('par 4, gross 5, strokes 0, cap 3 → net 5', () => {
    expect(calcNetScore(5, 0, 4, 3)).toBe(5)
  })

  // 1 stroke: raw = 5-1 = 4, cap = 4+1+3 = 8 → net 4
  test('par 4, gross 5, strokes 1, cap 3 → net 4', () => {
    expect(calcNetScore(5, 1, 4, 3)).toBe(4)
  })

  // 2 strokes: raw = 7-2 = 5, cap = 4+2+3 = 9 → net 5
  test('par 4, gross 7, strokes 2, cap 3 → net 5', () => {
    expect(calcNetScore(7, 2, 4, 3)).toBe(5)
  })

  // NET_MAX_OVER_PAR=3 cap triggered: gross=15 on par 3, strokes=2
  // raw = 15-2 = 13, cap = 3+2+3 = 8 → net 8
  test('Scenario C: gross 15 on par 3, strokes 2, cap 3 → net 8 (capped)', () => {
    expect(calcNetScore(15, 2, 3, 3)).toBe(8)
  })

  // NET_MAX_OVER_PAR=2 cap: gross=15 on par 3, strokes=2
  // raw = 13, cap = 3+2+2 = 7 → net 7
  test('Scenario C: gross 15 on par 3, strokes 2, cap 2 → net 7 (capped)', () => {
    expect(calcNetScore(15, 2, 3, 2)).toBe(7)
  })

  // Ace (hole-in-one) on par 3: gross=1, strokes=1
  // raw = 1-1 = 0, cap = 3+1+3 = 7 → net 0 (no cap needed)
  test('Ace on par 3, strokes 1 → net 0', () => {
    expect(calcNetScore(1, 1, 3, 3)).toBe(0)
  })

  // Eagle on par 5: gross=3, strokes=2
  // raw = 3-2 = 1, cap = 5+2+3 = 10 → net 1
  test('Eagle on par 5, strokes 2 → net 1', () => {
    expect(calcNetScore(3, 2, 5, 3)).toBe(1)
  })

  // High handicap stress: gross=10 on par 3, strokes=3
  // raw = 10-3 = 7, cap = 3+3+3 = 9 → net 7 (cap not triggered)
  test('gross 10 on par 3, strokes 3, cap 3 → net 7 (no cap)', () => {
    expect(calcNetScore(10, 3, 3, 3)).toBe(7)
  })

  // NET_MAX_OVER_PAR=3, scores exactly at cap: gross=10 on par 4, strokes=3
  // raw = 10-3 = 7, cap = 4+3+3 = 10 → net 7
  test('exact at cap: gross 10, par 4, strokes 3, cap 3 → net 7', () => {
    expect(calcNetScore(10, 3, 4, 3)).toBe(7)
  })

  // NET_MAX_OVER_PAR=3, just over cap: gross=15 on par 4, strokes=2
  // raw = 15-2 = 13, cap = 4+2+3 = 9 → net 9 (capped)
  test('over cap: gross 15, par 4, strokes 2, cap 3 → net 9 (capped)', () => {
    expect(calcNetScore(15, 2, 4, 3)).toBe(9)
  })

  // Scenario A spot-check: Ryan Day 1 H1 (par 4, gross 6, strokes 1, cap 3)
  // raw = 6-1 = 5, cap = 4+1+3 = 8 → net 5
  test('Scenario A: Ryan Day 1 H1 (par4, gross6, strokes1) → net5', () => {
    expect(calcNetScore(6, 1, 4, 3)).toBe(5)
  })

  // Scenario A: Jauch Day 1 H5 (par 4, gross 6, strokes 3, cap 3)
  // raw = 6-3 = 3, cap = 4+3+3 = 10 → net 3
  test('Scenario A: Jauch Day 1 H5 (par4, gross6, strokes3) → net3', () => {
    expect(calcNetScore(6, 3, 4, 3)).toBe(3)
  })
})

// ---------------------------------------------------------------------------
// Section 4: Playing Handicap — calcPlayingHandicap
// PH = player CH - min group CH
// ---------------------------------------------------------------------------

test.describe('Playing Handicap — calcPlayingHandicap', () => {
  // Low handicap player in group (gets PH=0)
  test('lowest player in group: CH=8, minCH=8 → PH=0', () => {
    expect(calcPlayingHandicap(8, 8)).toBe(0)
  })

  // Standard case
  test('CH=22, minCH=14 → PH=8', () => {
    expect(calcPlayingHandicap(22, 14)).toBe(8)
  })

  // High handicap vs scratch anchor
  test('CH=42, minCH=11 → PH=31', () => {
    expect(calcPlayingHandicap(42, 11)).toBe(31)
  })

  // Same CH
  test('CH=16, minCH=16 → PH=0', () => {
    expect(calcPlayingHandicap(16, 16)).toBe(0)
  })
})

// ---------------------------------------------------------------------------
// Section 5: NET_MAX_OVER_PAR comparison (2 vs 3)
// Verify the two settings produce different caps on the same gross score
// ---------------------------------------------------------------------------

test.describe('NET_MAX_OVER_PAR: 2 vs 3 comparison', () => {
  // gross=15 on par 3, strokes=2
  // cap3: 3+2+3=8 → net 8
  // cap2: 3+2+2=7 → net 7
  test('cap 3 → net 8 (par3, gross15, strokes2)', () => {
    expect(calcNetScore(15, 2, 3, 3)).toBe(8)
  })
  test('cap 2 → net 7 (par3, gross15, strokes2)', () => {
    expect(calcNetScore(15, 2, 3, 2)).toBe(7)
  })

  // gross=15 on par 4, strokes=3
  // cap3: 4+3+3=10 → net 10 (15-3=12, cap=10)
  // cap2: 4+3+2=9  → net 9
  test('cap 3 → net 10 (par4, gross15, strokes3)', () => {
    expect(calcNetScore(15, 3, 4, 3)).toBe(10)
  })
  test('cap 2 → net 9 (par4, gross15, strokes3)', () => {
    expect(calcNetScore(15, 3, 4, 2)).toBe(9)
  })

  // Score that doesn't hit either cap (par 4, gross 6, strokes 1)
  // raw = 5; cap3 = 8; cap2 = 7 → both return 5
  test('below both caps → same result (par4, gross6, strokes1)', () => {
    expect(calcNetScore(6, 1, 4, 3)).toBe(5)
    expect(calcNetScore(6, 1, 4, 2)).toBe(5)
  })
})
